### ISSUE TITLE
Tags for resources

### ISSUE THREAD

**Issue by anne17** [spraakbanken/metadata-api#1]
We want to have tags for our resources, (e.g. "newspapers"). Where should these live?

**Comment by StaffanMelin** [comment]
Liknande önskemål från Elena, gällande Kellym m fl lexikon: "Sen, skulle alla dessa kunnat taggas även mer "keywords" som L2, learner, eller något liknande, så att man får alla när man söker i resurs-filtret."

Ser nu att det faktiskt finns "keywoard" (lista) i YAML-mallen, och de importeras och visas, men det finns egentligen ingen sökfunktionalitet/länkning (kanske a la etiketter hos bloggen: https://spraakbanken.gu.se/blogg/etiketter).

**Comment by anne17** [comment]
Egentligen borde vi kunna stänga detta eftersom keywords nu finns, eller? Sökfunktionalitet är ju något som bör implementeras på webbsidan i så fall, och inte i API:et.

**Comment by StaffanMelin** [comment]
Ja, jag stänger den. Har redan lagt till en issue för hemsidan: https://github.com/spraakbanken/sbwebb-cms/issues/394
