### ISSUE TITLE
Metashare - change FullLoader to safe loader

### ISSUE THREAD

**Issue by StaffanMelin** [spraakbanken/metadata-api#24]
See #19.

File: create_metashare.py.

**Comment by arildm** [comment]
Wasn't this fixed in 8e04b38?

**Comment by StaffanMelin** [comment]
Not in create_metashare.py, right?

**Comment by StaffanMelin** [comment]
But I am editing it right now, so I can fix it! :)

**Comment by StaffanMelin** [comment]
Sorry, my bad. Looked at your commit -- I am working on a branch, and looked inside that one.

No problem merging afterwards, I hope! :)
