### ISSUE TITLE
Set updated when creating

### ISSUE THREAD

**Issue by StaffanMelin** [spraakbanken/metadata-api#28]
Always set updated to same date as created when creating a metadata resource.

**Comment by anne17** [comment]
Do you mean that the API should do this on the fly if the field "updated" is missing in the metadata?

**Comment by StaffanMelin** [comment]
Yeah, as a favor to the website.

But this is also a reminder to Sparv/Martin, for when he is creating YAML-files.

Does it make sense?

**Comment by anne17** [comment]
Yes, I just wanted to make sure I understood. [Sparv reminders don't live here though, I'm not even sure Martin reads these issues ;) ]

**Comment by StaffanMelin** [comment]
It is good that you ask (vet inte varför vi skriver på engelska :) ), I sent an e-mail to Martin and asked him.

We will (hopefuly) go through all of these issues on Wednesday. I have sometimes just jotted them down as a reminder for when you are coming back. :)

**Comment by StaffanMelin** [comment]
Validated through schema.

**Comment by MartinHammarstedt** [comment]
Sparv will automatically set the `updated` field.
For manually created metadata files, the schema validation (#12) will take care of the problem by rejecting files without an `updated` date.

**Comment by MartinHammarstedt** [comment]
Update: We decided to not require the `updated` field, as there are several resources for which we don't know the date.

Sparv will still automatically add the field though, so most resources will have it.
