### ISSUE TITLE
Make changes to the metadata format

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/metadata-api#34]
We will be making a few changes to the metadata format:

`references` ⇨ `other_references` (list of strings)
New field: `standard_reference` (string)

`languages.name_en` ⇨ `languages.name.eng` (string)
`languages.name_swe` ⇨ `languages.name.swe` (string)

- [x] Modify existing metadata files @MartinHammarstedt
- [x] Make any changes needed in the API @anne17
- [x] create_metashare.py @StaffanMelin 
- [x] gen_pids.py @StaffanMelin 
- [x] Make changes needed for the web site (import and presentation) @StaffanMelin
- [x] manually adding 'standard references' in metadata (Sasha?)
  - https://github.com/spraakbanken/metadata/issues/3
  - https://github.com/spraakbanken/metadata-api/issues/33

**Comment by StaffanMelin** [comment]
Var finns:

```
languages.name_en ⇨ languages.name.eng (string)
languages.name_swe ⇨ languages.name.swe (string)
```
@MartinHammarstedt ?

**Comment by StaffanMelin** [comment]
create_metashare.py verkar bara bry sig om `language_codes`.

**Comment by StaffanMelin** [comment]
No changes are need for either `create_metashare.py` nor `gen_pids.py` as they don't use the `references` field. It is a bit strange that references are not exported to the Clarin-repos, isn't it? I can't check the Clarin-repos as it gives errors for all resources...

**Comment by StaffanMelin** [comment]
For the web site I have to make changes in the resources import [MetadataClient.php](https://github.com/spraakbanken/sbwebb-cms/blob/master/web/modules/custom/sb_resources/src/MetadataClient.php), but that is not very time-consuming.

The new `standard_reference` field is a bit more work in several places, both code and Drupal UI.

**Comment by MartinHammarstedt** [comment]
> Where can I find:
> 
> ```
> languages.name_en ⇨ languages.name.eng (string)
> languages.name_swe ⇨ languages.name.swe (string)
> ```
> 
> @MartinHammarstedt ?
> 
> Ah, used `grep`. Eg `/corpus/aspacsvsbc.yaml`. But I can't find them in the templates, are they deprecated?

Not deprecated, probably just forgotten. I'll add them when I make my changes.

**Comment by StaffanMelin** [comment]
Website Drupal issue: https://github.com/spraakbanken/sbwebb-cms/issues/401
