### ISSUE TITLE
Eukalyptus download is labeled as "other", should be "corpus"

### ISSUE THREAD

**Issue by arildm** [spraakbanken/metadata-api#6]
https://ws.spraakbanken.gu.se/ws/metadata/?resource=eukalyptus

**Comment by anne17** [comment]
Pasting a discussion on this from Slack:

>Anne Schumacher
>Den där labeln genereras på följande sätt från nedladdningslänken:
>1. Om det står "/meningsmangder/" i länken blir labeln "korpus"
>2. Om det står "/frekvens/" i länken blir labeln "tokenfrekvenser"
>3. Om det står "/pub/lmf/" i länken blir labeln "lexikon"
>4. Om sista ledet i länken innehåller en punkt då blir labeln filnamnet istället.
>5. Om inget av det här stämmer då blir det "annat".
>
> Det är väldigt bruteforcigt och blir inte alltid bra, men det finns inte så mycket annan information om vad det är man laddar ner.
>
>Arild Matsson
>Finns det något annat i metashareformatet som kan hinta om att det i Eukalyptus fall borde vara "korpus"?
>
>Anne Schumacher
>Problemet är att man kan lägga in flera nedladdningsbara filer och det framgår inte riktigt vad de har för signifikans. Det vi har att gå på i det här fallet är det här:
>   ` <licenceInfo>`
>      `<licence lang="eng">Mixed</licence>`
>      `<licence lang="swe">Blandat</licence>`
>      `<restrictionsOfUse lang="eng">see license.txt</restrictionsOfUse>`
>     ` <restrictionsOfUse lang="swe">se license.txt</restrictionsOfUse>`
>      `<distributionAccessMedium>other</distributionAccessMedium>`
>      `<downloadLocation>http://demo.spraakdata.gu.se/gerlof/Eukalyptus_betas</downloadLocation>`
>    `</licenceInfo>`
>
>Sedan vet vi att eukalyptus-resursen är en korpus, men man kan ju som sagt lägga in andra licens-info-block i resursen som pekar på nåt annat nedladdningsbart än själva korpusen (t.ex. tokenfrekvenser).

**Comment by StaffanMelin** [comment]
It is labeled as "corpus" now.  
[](https://ws.spraakbanken.gu.se/ws/metadata/?resource=eukalyptus)
gives
` "type": "corpus", `
